// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lxpiwepsbzohfnvmmqse.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx4cGl3ZXBzYnpvaGZudm1tcXNlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ3OTA0NzcsImV4cCI6MjA2MDM2NjQ3N30.LK_vyrttBRNV_0-EGbSK7DVuOQE5p7cDEndwoo_ayzA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);